CREATE TABLE IF NOT EXISTS "properties" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(256) NOT NULL,
	"slug" varchar(256) NOT NULL,
	"description" varchar(256) NOT NULL,
	"address" varchar(256) NOT NULL,
	"city" varchar(256) NOT NULL,
	"state" varchar(256) NOT NULL,
	"country" varchar(256) NOT NULL,
	"neighborhood" varchar(256),
	"street" varchar(256),
	"external_number" varchar(256),
	"internal_number" varchar(256),
	"location" jsonb NOT NULL,
	"price" integer NOT NULL,
	"area" jsonb NOT NULL,
	"garage" integer NOT NULL,
	"images" varchar(256)[],
	"amenities" varchar(256)[],
	"bedrooms" integer NOT NULL,
	"bathrooms" integer NOT NULL,
	"image" varchar(256),
	"owner" varchar(256),
	"virtualTourUrl" varchar(256),
	"video" varchar(256),
	"antiquity" integer NOT NULL,
	"propertyStatus" varchar(256),
	"type" varchar(256) NOT NULL,
	"blockchainId" varchar(256) NOT NULL,
	"category" varchar(256) NOT NULL,
	"partner" varchar(256),
	"created_at" timestamp DEFAULT now() NOT NULL
);
