ALTER TABLE "users" ALTER COLUMN "name" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "residence" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "lastname" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "password" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "last_login" SET DATA TYPE varchar;
ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL;