CREATE TABLE IF NOT EXISTS "posts" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(256) NOT NULL,
	"slug" varchar(256),
	"author" varchar(256),
	"category" varchar(256),
	"description" text,
	"tags" varchar(256)[],
	"excerpt" varchar(256),
	"content" varchar(256),
	"featuredImage" varchar(256),
	"socialImage" varchar(256),
	"seoTitle" varchar(256),
	"seoDescription" varchar(256),
	"seoKeywords" varchar(256)[],
	"canonicalUrl" varchar(256),
	"relatedPosts" varchar(256)[],
	"commentsEnabled" boolean,
	"comments" jsonb NOT NULL,
	"likes" integer,
	"shares" integer,
	"views" integer,
	"rating" integer,
	"language" varchar(256),
	"duration" varchar(256),
	"location" varchar(256),
	"source" varchar(256),
	"inGeneral" boolean,
	"company" varchar(256)
);
