import {
  boolean,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

export const posts = pgTable("posts", {
  id: uuid("id").defaultRandom().notNull(),
  title: varchar("title", { length: 256 }).notNull(),
  slug: varchar("slug", { length: 256 }),
  author: varchar("author", { length: 256 }),
  category: varchar("category", { length: 256 }),
  description: text("description"),
  tags: varchar("tags", { length: 256 }).array(),
  excerpt: text("excerpt"),
  content: text("content"),
  featuredImage: varchar("featuredImage", { length: 256 }),
  socialImage: varchar("socialImage", { length: 256 }),
  seoTitle: varchar("seoTitle", { length: 256 }),
  seoDescription: text("seoDescription"),
  seoKeywords: varchar("seoKeywords", { length: 256 }).array(),
  canonicalUrl: varchar("canonicalUrl", { length: 256 }),
  relatedPosts: varchar("relatedPosts", { length: 256 }).array(),
  commentsEnabled: boolean("commentsEnabled"),
  comments: jsonb("comments"),
  likes: integer("likes"),
  shares: integer("shares"),
  views: integer("views"),
  rating: integer("rating"),
  language: varchar("language", { length: 256 }),
  duration: varchar("duration", { length: 256 }),
  location: varchar("location", { length: 256 }),
  source: varchar("source", { length: 256 }),
  inGeneral: boolean("inGeneral"),
  company: varchar("company", { length: 256 }),
  status: varchar("status", { length: 256 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
